<a href="https://colab.research.google.com/github/mac-raj/Numpy_PyLib/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction of NumPy

In [1]:
# Numpy provides efficent storage
# It is Provide better ways of handling data for processing
# It is fast 
# It is easy to learn
# Numpy uses realative less memory to store data in pathon and c language we use pointer 

import numpy as np 
# you can use whatever name you want to in place of np

In [2]:
print("Hello Raj")

Hello Raj


Use np.array to create list [] ,tuple () and set {}

In [3]:
myarr = np.array([3,5,746432752,9,20], np.int8)

In [4]:
myarr

array([  3,   5, -16,   9,  20], dtype=int8)

In [5]:
myarr[2]

-16

In [6]:
twodarr= np.array([[10,20,30,40,50]], np.int32)

In [7]:
twodarr[0,2]

30

In [8]:
# .shape is use for calculate number of rows and column 

myarr.shape

(5,)

In [9]:
twodarr.shape

(1, 5)

In [10]:
myarr.dtype

dtype('int8')

In [11]:
twodarr[0,2]=100

In [12]:
twodarr

array([[ 10,  20, 100,  40,  50]], dtype=int32)

In [13]:
listarray= np.array([[1,2,3,4],[5,6,7,8],[3,4,5,6]])

Conversion from other Python structure like list and tuple

In [14]:
listarray

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 4, 5, 6]])

In [15]:
listarray.dtype

dtype('int64')

In [16]:
listarray.shape

(3, 4)

In [17]:
listarray.size

12

In [18]:
# set dtype is object
np.array({12,34,56})

array({56, 34, 12}, dtype=object)

Creating Tuple


In [19]:
# tuple
np.array((10,20,30))

array([10, 20, 30])

In [20]:
# creating array which all element is filled by zero
zeros =np.zeros((2,5))

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
zeros.dtype

dtype('float64')

In [23]:
# printing 0 to n-1 using range 
rng=np.arange(20)

In [24]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
lspace =np.linspace(1,5,10)

In [26]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [27]:
emp=np.empty((4,6))

In [28]:
emp

array([[1.63003403e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [29]:
emp_like = np.empty_like(emp)

In [30]:
emp_like

array([[1.63003403e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [31]:
ide = np.identity(3)

In [32]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
ide.shape

(3, 3)

In [34]:
range = np.arange(9)

In [35]:
range

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
# range allowed only for multiple
range.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
range.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

NumPy Axis

In [38]:
ar = [[1,2,3],[4,5,6],[6,7,8]]

In [39]:
arr= np.array(ar)

In [40]:
arr.sum(axis=0)

array([11, 14, 17])

In [41]:
arr.sum(axis=1)

array([ 6, 15, 21])

In [42]:
# transpose matrix
arr=arr.T

In [43]:
arr

array([[1, 4, 6],
       [2, 5, 7],
       [3, 6, 8]])

In [44]:
arr.sum(axis=0)

array([ 6, 15, 21])

In [45]:
arr.sum(axis=1)

array([11, 14, 17])

In [46]:
arr.flat

In [47]:
for item in arr.flat:
  print(item)

1
4
6
2
5
7
3
6
8


In [48]:
# no of dimension 
arr.ndim

2

In [49]:
arr.size

9

In [50]:
# How many byte of memory consume by memory
arr.nbytes

72

In [51]:
one =np.array([1,23,4,5,6,7])

In [52]:
one

array([ 1, 23,  4,  5,  6,  7])

In [53]:
# Maxmium element in an array
one.argmax()

1

In [54]:
# Minimum element in an array
one.argmin()

0

In [55]:
#Give the array of index in sorted order
one.argsort()

array([0, 2, 3, 4, 5, 1])

In [56]:
twodim =np.array([[10,2,3],[4,5,6],[6,7,8]])

In [57]:
twodim

array([[10,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8]])

In [58]:
twodim.argmin()

1

In [59]:
twodim.argmax()

0

In [60]:
twodim.argmin(axis=0)

array([1, 0, 0])

In [61]:
twodim.argmax(axis=1)

array([0, 2, 2])

In [62]:
twodim.ravel()

array([10,  2,  3,  4,  5,  6,  6,  7,  8])

In [63]:
twodim.reshape(9,1)

array([[10],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 6],
       [ 7],
       [ 8]])

In [64]:
ar1 =np.array([[1,2,3],[3,4,5],[5,6,7]])

In [65]:
ar1

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [66]:
ar2= np.array([[9,8,7],[6,7,5],[3,4,5]])

In [67]:
ar2

array([[9, 8, 7],
       [6, 7, 5],
       [3, 4, 5]])

In [68]:
# summation of matrix
ar3=ar1+ar2

In [69]:
ar3

array([[10, 10, 10],
       [ 9, 11, 10],
       [ 8, 10, 12]])

In [70]:
# multiplication of matrix
ar4=ar1*ar2

In [71]:
ar4

array([[ 9, 16, 21],
       [18, 28, 25],
       [15, 24, 35]])

In [72]:
# square root
np.sqrt(ar4)

array([[3.        , 4.        , 4.58257569],
       [4.24264069, 5.29150262, 5.        ],
       [3.87298335, 4.89897949, 5.91607978]])

In [73]:
# sum of all element in the matrix
ar4.sum()

191

In [74]:
# Max in the matrix
ar4.min()

9

In [75]:
ar4.max()

35

In [76]:
whr=np.where(ar4>10)

In [77]:
whr

(array([0, 0, 1, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2, 0, 1, 2]))

In [78]:
type(whr)

tuple

In [79]:
np.count_nonzero(ar4)

9

In [80]:
np.nonzero(ar4)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [81]:
import sys

In [82]:
py_ar=[0,4,44,2]

In [83]:
np_ar=np.array(py_ar)

In [84]:
sys.getsizeof(1)*len(py_ar)

112

In [85]:
np_ar.itemsize*np_ar.size

32